### ISSUE TITLE
Vertaisarviointi 2

### ISSUE THREAD

**Issue by shiftleino** [sampsaoinonen/tsoha-martketplace#2]
Sovellus näyttää olevan yleisesti hyvällä mallilla ja toiminnallisuuksia on todella paljon. Alla eriteltynä muutamia parannusehdotuksia ja ajatuksia sovelluksen toiminnallisuuksista.

**Käyttökokemus**
- Kun käyttäjä ei ole kirjautunut ja selaa tuotteita, hänelle näytetään "send message" linkki, joka ei tällä hetkellä johda mihinkään. Tämä linkki voisi näkyä vain kirjautuneille käyttäjille.
- Ilmoitus onnistuneesta kirjautumisesta voisi tulla esimerkiksi vihreällä tekstillä sivun yläosaan (nyt sivun alaosassa)
- En onnistunut lähettämään viestiä toiselle käyttäjälle (404 error).
- Jos jää aikaa, sovelluksen layoutia voisi muuttaa olemaan vähän vähemmän "bootsrappy" esimerkiksi muuttamalla bootstrapin värimaailmaa css-tiedostolla.

**Koodi**
- Koodia voisi ryhmitellä eri hakemistoihin rakenteen selkeyttämiseksi
- CSRF-tokenia ei tarvitse lähettää funktiolle parametrina, vaan funktio voi saada sen myös itse flaskin requestilla (request.form[""]). Tosin nykyinenkin tapa on ihan selkeä.

Muuta huomautettavaa tms. en sovelluksesta löytänyt. Hyvää työtä!

**Comment by sampsaoinonen** [comment]
Tuotteissa oleva "send message"-linkki on vielä vaiheessa, mutta varsinaiset viestin lähetys-ominaisuudet toimii kyllä ("new message"). Flash messagen voisi tosiaan laittaa ylös ja "error"-viestit eri värillä. Ohjelman jaottelua eri tiedostoihin ja niiden tehtäviä mietin aika paljon. En ole varma selkeyttääkö kansiot sinänsä, jos niihin tulee yksi tiedosto tms. Harkintaan sekin joka tapauksessa :)  Kiitos palautteesta ja tsemiä kurssiin!

**Comment by sampsaoinonen** [comment]
Tuotteissa oleva "send message"-linkki on vielä vaiheessa, mutta varsinaiset viestin lähetys-ominaisuudet toimii kyllä ("new message"). Flash messagen voisi tosiaan laittaa ylös ja "error"-viestit eri värillä. Ohjelman jaottelua eri tiedostoihin ja niiden tehtäviä mietin aika paljon. Pistetään harkintaan selkiyttäisikö kansioiden lisääminen vielä lisää. Kiitos palautteesta ja tsemiä kurssiin!
